# Generated by Django 5.2.6 on 2025-09-07 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo del residente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del residente', max_length=100)),
                ('cedula', models.CharField(help_text='Cédula de identidad', max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_perfil', models.ImageField(help_text='Foto para reconocimiento facial', upload_to='residentes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_visita', models.DateField()),
                ('hora_entrada_prevista', models.TimeField(blank=True, null=True)),
                ('hora_salida_prevista', models.TimeField(blank=True, null=True)),
                ('foto_perfil', models.ImageField(blank=True, help_text='Foto opcional para reconocimiento', null=True, upload_to='visitantes/')),
                ('autorizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitantes_autorizados', to='api.residente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('foto_capturada', models.ImageField(help_text='Foto capturada por la cámara en el momento del acceso', upload_to='capturas_acceso/')),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.residente')),
                ('visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.visitante')),
            ],
        ),
    ]
