# Generated by Django 5.2.6 on 2025-09-07 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadHabitacional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(help_text='Ej: A-101, Casa 25', max_length=10, unique=True)),
                ('propietario', models.CharField(help_text='Nombre del dueño legal', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='residente',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='api.unidadhabitacional'),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('residente_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='api.residente')),
            ],
        ),
    ]
